# Generated by Django 5.1.1 on 2024-11-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
